/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author ZENDIA AMELIA
 */
   public class AdminLaundry extends javax.swing.JFrame {
   static DefaultTableModel model1 = new DefaultTableModel(new String[]{"ID", "Nama Pembeli", "Alamat", "Tanggal Pesan", "Jenis Baju", "Jenis Layanan", "Jenis Paket", "Total Berat", "Tgl Ambil", "Total Biaya"}, 0);
    /**
     * Creates new form LoginAdminLaundry
     */
    private TBAdmin admin = new  TBAdmin();
    public AdminLaundry() {
        initComponents();
        loadDataPemesanan();
        
       tabeldata.getSelectionModel().addListSelectionListener(event -> {
        int selectedRow = tabeldata.getSelectedRow();
        if (selectedRow != -1) {
            idpembeliadmin.setText(model1.getValueAt(selectedRow, 0).toString());
            NamaPembeli.setText(model1.getValueAt(selectedRow, 1).toString());
            tanggalambiladmin.setText(model1.getValueAt(selectedRow, 8).toString());
            totalbiayaadmin.setText(model1.getValueAt(selectedRow, 9).toString());
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idAdmin = new javax.swing.JTextField();
        NamaPembeli = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        tanggalambiladmin = new javax.swing.JTextField();
        ButtonHapus = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        idpembeliadmin = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        totalbiayaadmin = new javax.swing.JTextField();
        buttontotaladmin = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        totalpointadmin = new javax.swing.JTextField();

        idAdmin.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.lightGray));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Selamat Datang");

        jLabel7.setFont(new java.awt.Font("Square721 BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("LAUNDRY CLICKCLEAN ");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/benar2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel29)
                .addGap(209, 209, 209)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel13.setBackground(new java.awt.Color(0, 0, 102));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Data Pemesanan Pembeli Laundry");

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pembeli", "Jenis Layanan", "Jenis Baju", "Jenis Paket", "Tanggal Pesan", "Tanggal Ambil", "Total Berat", "Total Biaya"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Tanggal Ambil :");

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Update");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Id Pembeli :");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Total Biaya :");

        totalbiayaadmin.setEditable(false);

        buttontotaladmin.setText("Total");
        buttontotaladmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontotaladminActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Total Point :");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(514, 514, 514)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                        .addComponent(ButtonTambah)
                                        .addGap(56, 56, 56)))))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(ButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonHapus))
                            .addComponent(totalbiayaadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(totalpointadmin))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttontotaladmin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanggalambiladmin, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(idpembeliadmin)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tanggalambiladmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(totalbiayaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idpembeliadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42)
                        .addComponent(totalpointadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(buttontotaladmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonTambah))
                .addGap(56, 56, 56))
        );

        jPanel4.add(jPanel13, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Penyimpanan Data Pembeli", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttontotaladminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontotaladminActionPerformed
        // TODO add your handling code here:
    try {
            int totalBiaya = 0;

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_aplikasilaundry", "root", "");

            String queryPembeli = "SELECT total_berat, jenis_baju, jenis_layanan, jenis_paket FROM tb_pembeli WHERE id_pembeli = ?";
            PreparedStatement stmtPembeli = conn.prepareStatement(queryPembeli);
            int id_pembeli = Integer.parseInt(idpembeliadmin.getText()); // Ambil ID dari input admin
            stmtPembeli.setInt(1, id_pembeli);
            ResultSet rsPembeli = stmtPembeli.executeQuery();

            if (rsPembeli.next()) {
                int berat = rsPembeli.getInt("total_berat");
                int hargaPerKilo = 10000;
                totalBiaya += berat * hargaPerKilo;

                String jenisBaju = rsPembeli.getString("jenis_baju");
                if (jenisBaju != null) {
                    String[] jenisBajuArray = jenisBaju.split(", ");
                    for (String baju : jenisBajuArray) {
                        switch (baju.trim()) { // Menggunakan trim() untuk menghilangkan spasi ekstra
                            case "Seprai" -> totalBiaya += 5000;
                            case "Selimut" -> totalBiaya += 5000;
                            case "Boneka" -> totalBiaya += 3000;
                            case "Baju Bahan Khusus" -> totalBiaya += 5000;
                            case "Baju" -> totalBiaya += 0; // Tidak ada biaya tambahan
                            default -> System.out.println("Jenis baju tidak dikenal: " + baju); // Logging
                        }
                    }
                }


                String jenisLayanan = rsPembeli.getString("jenis_layanan");
                if (jenisLayanan != null) {
                    String[] jenisLayananArray = jenisLayanan.split(", ");
                    for (String layanan : jenisLayananArray) {
                        switch (layanan.trim()) {
                            case "Cuci Kering" -> totalBiaya += 5000;
                            case "Cuci Basah" -> totalBiaya += 5000;
                            case "Cuci Kering, Cuci Basah, Setrika" -> totalBiaya += 10000;
                            default -> System.out.println("Jenis layanan tidak dikenal: " + layanan); // Logging
                        }
                    }
                }

                String jenisPaket = rsPembeli.getString("jenis_paket");
                if (jenisPaket != null) {
                    switch (jenisPaket.trim()) {
                        case "Reguler" -> totalBiaya += 5000;
                        case "High Quality" -> totalBiaya += 10000;
                        default -> System.out.println("Jenis paket tidak dikenal: " + jenisPaket); // Logging
                    }
                }
            }

            // Tampilkan hasil perhitungan di totalbiayaadmin
            totalbiayaadmin.setText("Rp " + totalBiaya);

            // Menutup koneksi
            rsPembeli.close();
            stmtPembeli.close();
            conn.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengakses database!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttontotaladminActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        // Mendapatkan nilai dari JTextField
        String val_id_admin = idAdmin.getText();
        String val_tgl_ambil = tanggalambiladmin.getText();
        String val_total = totalbiayaadmin.getText();
        String val_id_pembeli = idpembeliadmin.getText();
        String val_total_point = totalpointadmin.getText();
        String val_nama = NamaPembeli.getText();

        int id_pembeli = Integer.parseInt(val_id_pembeli);
        double totalBiaya = Double.parseDouble(val_total.replace("Rp ", "").replace(",", ""));

        // Cek jika poin >= 1 dan berikan diskon
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_aplikasilaundry", "root", "");

            int poin = 0;
            String queryAdmin = "SELECT total_point FROM tb_admin WHERE id_pembeli = ?";
            PreparedStatement stmtAdmin = conn.prepareStatement(queryAdmin);
            stmtAdmin.setInt(1, id_pembeli);
            ResultSet rsAdmin = stmtAdmin.executeQuery();

            if (rsAdmin.next()) {
                poin = rsAdmin.getInt("total_point");
            }

            if (totalBiaya > 50000) {
                poin += 1;
            }

            // Cek jika poin mencapai 1 untuk berikan diskon
            if (poin >= 1) {
                totalBiaya *= 0.9; // Diskon 10%
                poin = 0; // Reset poin setelah diskon
                JOptionPane.showMessageDialog(null, "Selamat! Anda mendapatkan diskon 10% karena pembelian di atas Rp.50.000" + val_nama);
            }

            // Update total point di database
            String updatePoin = "UPDATE tb_admin SET total_point = ? WHERE id_pembeli = ?";
            PreparedStatement stmtUpdatePoin = conn.prepareStatement(updatePoin);
            stmtUpdatePoin.setInt(1, poin);
            stmtUpdatePoin.setInt(2, id_pembeli);
            stmtUpdatePoin.executeUpdate();

            // Membuat objek BagianAdmin dengan total biaya yang sudah didiskon
            BagianAdmin brg = new BagianAdmin(
                0,
                id_pembeli,
                poin,
                String.format("Rp %,d", (int) totalBiaya),
                val_tgl_ambil,
                val_nama
            );

            // Masukkan data ke database
            admin.InsertAdmin(brg);
            loadDataPemesanan();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            rsAdmin.close();
            stmtAdmin.close();
            stmtUpdatePoin.close();
            conn.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int selectedRow = tabeldata.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan diubah");
            return;
        }

        // Mendapatkan nilai ID dari tabel dan memeriksa apakah nilainya tidak kosong
        Object idValue = model1.getValueAt(selectedRow, 0);

        if (idValue == null || idValue.toString().isEmpty()) {
            System.out.println("ID tidak valid atau kosong.");
            return;
        }

        try {
            int id = Integer.parseInt(idValue.toString());
            String tanggal_ambil = tanggalambiladmin.getText();
            int id_pembeli = Integer.parseInt(idpembeliadmin.getText());
            String total_biaya = totalbiayaadmin.getText();
            int total_point = Integer.parseInt(totalpointadmin.getText());
            String nama = NamaPembeli.getText();

            // Membuat objek BarangProyek dengan data yang diperbarui
            BagianAdmin bagian = new BagianAdmin(id, id_pembeli, total_point, total_biaya, tanggal_ambil, nama);


            // Mengupdate data proyek di database
            try {
                admin.UpdateAdmin(bagian);
                loadDataPemesanan();
                JOptionPane.showMessageDialog(this,"Data berhasil diubah");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this,"Tidak dapat mengubah data, error: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            System.out.println("ID atau Durasi tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabeldata.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("Pilih baris yang akan dihapus");
            return;
        }

        String idString = model1.getValueAt(selectedRow, 0).toString();
        int id = Integer.parseInt(idString);

        try {
            admin.deletePembeli(id);
            loadDataPemesanan();
            JOptionPane.showMessageDialog(this,"Data berhasil dihapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"Tidak dapat menghapus data, error: " + e.getMessage());
            }
    }//GEN-LAST:event_ButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void loadDataPemesanan() {
    model1.setRowCount(0);
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_aplikasilaundry", "root", ""); // Koneksi ke database
        Statement stmt = conn.createStatement(); // Membuat statement
        ResultSet rs = stmt.executeQuery(
        "SELECT tb_pembeli.id_pembeli, tb_pembeli.nama_pembeli, tb_pembeli.alamat, tb_pembeli.tanggal_pesan, tb_pembeli.jenis_baju, " +
        "tb_pembeli.jenis_layanan, tb_pembeli.jenis_paket, tb_pembeli.total_berat, tb_admin.tanggal_ambil, tb_admin.total_biaya, tb_admin.total_point " +
        "FROM tb_pembeli " +
        "JOIN tb_admin ON tb_pembeli.id_pembeli = tb_admin.id_pembeli"
        );


        model1.setRowCount(0); // Kosongkan tabel sebelum menambahkan data baru

        // Loop melalui hasil query dan tambahkan ke model tabel
        while (rs.next()) {
            String id_pembeli = rs.getString("id_pembeli");
            String nama_pembeli = rs.getString("nama_pembeli");
            String alamat = rs.getString("alamat");
            String tanggalpesan = rs.getString("tanggal_pesan");
            String jenisbaju = rs.getString("jenis_baju");
            String jenislayanan = rs.getString("jenis_layanan");
            String jenispaket = rs.getString("jenis_paket");
            String totalberat = rs.getString("total_berat");
            String tgl_ambil = rs.getString("tanggal_ambil");
            String total = rs.getString("total_biaya");
            String point = rs.getString("total_point");

            model1.addRow(new Object[]{id_pembeli, nama_pembeli, alamat, tanggalpesan, jenisbaju, jenislayanan, jenispaket, totalberat, tgl_ambil, total, point});
        }

        // Menutup koneksi dan statement setelah selesai
        rs.close();
        stmt.close();
        conn.close();

        } catch (SQLException e) {
            e.printStackTrace(); // Menampilkan error jika ada
        }
    
        // Set model ke tabel setelah data dimasukkan
        tabeldata.setModel(model1);

    }
    
    public String getDataPembeli(String namaPembeli) {
        for (int row = 0; row < tabeldata.getRowCount(); row++) {
            String nama = tabeldata.getValueAt(row, 1).toString(); 
            if (nama.equalsIgnoreCase(namaPembeli)) {
                // Ambil data dari setiap kolom di baris yang sesuai
                String id = tabeldata.getValueAt(row, 0).toString();
                String alamat = tabeldata.getValueAt(row, 2).toString();
                String tanggalPesan = tabeldata.getValueAt(row, 3).toString();
                String jenisBaju = tabeldata.getValueAt(row, 4).toString();
                String jenisLayanan = tabeldata.getValueAt(row, 5).toString();
                String jenisPaket = tabeldata.getValueAt(row, 6).toString();
                String totalBerat = tabeldata.getValueAt(row, 7).toString();
                String tanggalAmbil = tabeldata.getValueAt(row, 8).toString();
                String totalBiaya = tabeldata.getValueAt(row, 9).toString();
                
                // Format data menjadi string nota
                return "ID: " + id + "\n" +
                       "Nama: " + nama + "\n" +
                       "Alamat: " + alamat + "\n" +
                       "Tanggal Pesan: " + tanggalPesan + "\n" +
                       "Jenis Baju: " + jenisBaju + "\n" +
                       "Jenis Layanan: " + jenisLayanan + "\n" +
                       "Jenis Paket: " + jenisPaket + "\n" +
                       "Total Berat: " + totalBerat + " kg\n" +
                       "Tanggal Ambil: " + tanggalAmbil + "\n" +
                       "Total Biaya: " + totalBiaya;
            }
        }
        return "Data tidak ditemukan";
    }


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTextField NamaPembeli;
    private javax.swing.JButton buttontotaladmin;
    private javax.swing.JTextField idAdmin;
    private javax.swing.JTextField idpembeliadmin;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField tanggalambiladmin;
    private javax.swing.JTextField totalbiayaadmin;
    private javax.swing.JTextField totalpointadmin;
    // End of variables declaration//GEN-END:variables
}
