/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
/**
 *
 * @author ZENDIA AMELIA
 */

public class PembeliLaundry extends javax.swing.JFrame {
    /**
     * Creates new form LoginPembeli
     */
    private AdminLaundry adminLaundry;
    private TBPembeli Pemesanan = new TBPembeli();
    private boolean isEditing = false;
    private int id;
    public PembeliLaundry(AdminLaundry adminLaundry) {
        initComponents(); 
        this.adminLaundry = adminLaundry;
    }
    
    private void tampilkanNota() {
        String namaPembeli = NamaBukti.getText();
        if (!namaPembeli.isEmpty()) {
            String nota = adminLaundry.getDataPembeli(namaPembeli);
            hasilbuktipembeli.setText(nota);
        } else {
            hasilbuktipembeli.setText("Masukkan nama pembeli terlebih dahulu.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        idpembeli = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        namapembeli = new javax.swing.JTextField();
        totalberatpembeli = new javax.swing.JTextField();
        alamatpembeli = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttonbatalpembeli = new javax.swing.JButton();
        buttonresetpembeli = new javax.swing.JButton();
        buttonpesansekarangpebeli = new javax.swing.JButton();
        baju = new javax.swing.JCheckBox();
        seprai = new javax.swing.JCheckBox();
        selimut = new javax.swing.JCheckBox();
        boneka = new javax.swing.JCheckBox();
        bajubahankhusus = new javax.swing.JCheckBox();
        tanggalpesanpembeli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonkembalipembeli = new javax.swing.JButton();
        cucikering = new javax.swing.JRadioButton();
        cucibasah = new javax.swing.JRadioButton();
        ketiganya = new javax.swing.JRadioButton();
        highquality = new javax.swing.JRadioButton();
        reguler = new javax.swing.JRadioButton();
        editpembeli = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        buttonbuktipembeli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasilbuktipembeli = new javax.swing.JTextArea();
        buttonkeluar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        NamaBukti = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.lightGray));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Selamat Datang");

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("LAUNDRY CLICKCLEAN ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/benar2.png"))); // NOI18N

        jLabel18.setBackground(new java.awt.Color(0, 0, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Silahkan Melakukan Pemesanan Laundry Anda");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(173, 173, 173))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Masukkan Alamat Anda :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Masukkan Nama Anda :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Masukkan Total Berat Kg :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Masukkan Tanggal Pesan :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Jenis Baju  :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(" Jenis Paket :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Jenis Layanan :");

        buttonbatalpembeli.setText("Batal");
        buttonbatalpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbatalpembeliActionPerformed(evt);
            }
        });

        buttonresetpembeli.setText("Reset");
        buttonresetpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresetpembeliActionPerformed(evt);
            }
        });

        buttonpesansekarangpebeli.setText("Pesan Sekarang");
        buttonpesansekarangpebeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpesansekarangpebeliActionPerformed(evt);
            }
        });

        baju.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        baju.setForeground(new java.awt.Color(255, 255, 255));
        baju.setText("Baju");

        seprai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seprai.setForeground(new java.awt.Color(255, 255, 255));
        seprai.setText("Seprai");

        selimut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selimut.setForeground(new java.awt.Color(255, 255, 255));
        selimut.setText("Selimut");

        boneka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boneka.setForeground(new java.awt.Color(255, 255, 255));
        boneka.setText("Boneka");

        bajubahankhusus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bajubahankhusus.setForeground(new java.awt.Color(255, 255, 255));
        bajubahankhusus.setText("Baju Bahan Khusus");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("------------------------------------------------------------------------------------------------------------------------------------");

        buttonkembalipembeli.setText("Kembali");
        buttonkembalipembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkembalipembeliActionPerformed(evt);
            }
        });

        buttonGroup1.add(cucikering);
        cucikering.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cucikering.setForeground(new java.awt.Color(255, 255, 255));
        cucikering.setText("Cuci Kering");

        buttonGroup1.add(cucibasah);
        cucibasah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cucibasah.setForeground(new java.awt.Color(255, 255, 255));
        cucibasah.setText("Cuci Basah");

        buttonGroup1.add(ketiganya);
        ketiganya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ketiganya.setForeground(new java.awt.Color(255, 255, 255));
        ketiganya.setText("Cuci Kering, Cuci Basah, Seterika");

        buttonGroup2.add(highquality);
        highquality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        highquality.setForeground(new java.awt.Color(255, 255, 255));
        highquality.setText("High Quality");

        buttonGroup2.add(reguler);
        reguler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reguler.setForeground(new java.awt.Color(255, 255, 255));
        reguler.setText("Reguler");

        editpembeli.setText("Edit");
        editpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpembeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalberatpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(baju, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(seprai, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(selimut, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(boneka, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bajubahankhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cucikering)
                                            .addComponent(reguler))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(cucibasah)
                                                .addGap(18, 18, 18)
                                                .addComponent(ketiganya, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(highquality)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(buttonkembalipembeli)
                                .addGap(18, 18, 18)
                                .addComponent(editpembeli)
                                .addGap(328, 328, 328))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalpesanpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonpesansekarangpebeli, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonresetpembeli)
                .addGap(18, 18, 18)
                .addComponent(buttonbatalpembeli)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(namapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(totalberatpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(alamatpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(tanggalpesanpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(baju)
                    .addComponent(seprai)
                    .addComponent(selimut)
                    .addComponent(boneka)
                    .addComponent(bajubahankhusus))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cucibasah)
                    .addComponent(ketiganya)
                    .addComponent(cucikering))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(highquality)
                    .addComponent(reguler))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonpesansekarangpebeli)
                    .addComponent(buttonresetpembeli)
                    .addComponent(buttonbatalpembeli)
                    .addComponent(buttonkembalipembeli)
                    .addComponent(editpembeli))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Pemesanan Laundry", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Selamat Datang");

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("LAUNDRY CLICKCLEAN ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/benar2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(94, 94, 94)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bukti Pemesanan Laundry Anda");

        buttonbuktipembeli.setText("Bukti");
        buttonbuktipembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbuktipembeliActionPerformed(evt);
            }
        });

        hasilbuktipembeli.setColumns(20);
        hasilbuktipembeli.setRows(5);
        jScrollPane1.setViewportView(hasilbuktipembeli);

        buttonkeluar.setText("Keluar");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama :");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Masukkan Nama Anda Untuk Melihat Pesanan Laundry Anda");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonkeluar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(NamaBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(buttonbuktipembeli))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaBukti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonbuktipembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buttonkeluar)
                .addGap(17, 17, 17))
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Bukti Pemesanan", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonkembalipembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkembalipembeliActionPerformed
        // TODO add your handling code here:
        LoginPembeli LoginPembeli = new LoginPembeli();
        LoginPembeli.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonkembalipembeliActionPerformed

    private void buttonbatalpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbatalpembeliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonbatalpembeliActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void buttonpesansekarangpebeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpesansekarangpebeliActionPerformed
        // TODO add your handling code here:
       
        String val_id_pembeli = idpembeli.getText();
        String val_nama = namapembeli.getText();
        String val_totalBerat = totalberatpembeli.getText();
        String val_alamat = alamatpembeli.getText();
        String val_tanggalPesan = tanggalpesanpembeli.getText();
        
        
        StringBuilder val_jenisbajuBuilder = new StringBuilder();
        if (baju.isSelected()) val_jenisbajuBuilder.append("Baju, ");
        if (seprai.isSelected()) val_jenisbajuBuilder.append("Seprai, ");
        if (selimut.isSelected()) val_jenisbajuBuilder.append("Selimut, ");
        if (boneka.isSelected()) val_jenisbajuBuilder.append("Boneka, ");
        if (bajubahankhusus.isSelected()) val_jenisbajuBuilder.append("Baju Bahan Khusus, ");
        String val_jenis_baju = val_jenisbajuBuilder.toString().replaceAll(", $", ""); // pastikan string sesuai dengan kolom

        
        String val_jenisLayanan;
        if (cucikering.isSelected()) {
            val_jenisLayanan = "Cuci Kering";
        } else if (cucibasah.isSelected()) {
            val_jenisLayanan = "Cuci Basah";
        } else if (ketiganya.isSelected()) {
            val_jenisLayanan = "Cuci Kering, Cuci Basah, Setrika";
        } else {
            val_jenisLayanan = ""; 
        }

        String val_jenisPaket;
        if (reguler.isSelected()) {
            val_jenisPaket = "Reguler";
        } else if (highquality.isSelected()) {
            val_jenisPaket = "High Quality";
        } else {
            val_jenisPaket = ""; // Jika tidak dipilih, beri nilai kosong
        }        
      
        
       
        BagianPembeli brg = new BagianPembeli(
            0,
            Integer.parseInt(val_totalBerat),
            val_nama,
            val_alamat,
            val_tanggalPesan,
            val_jenis_baju,
            val_jenisLayanan,
            val_jenisPaket
        );

        try {
            Pemesanan.InsertPembeli(brg);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Tidak dapat menambahkan data, error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonpesansekarangpebeliActionPerformed

    private void buttonresetpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonresetpembeliActionPerformed
        // TODO add your handling code here:
        namapembeli.setText("");
        totalberatpembeli.setText("");
        alamatpembeli.setText("");
        tanggalpesanpembeli.setText("");
        baju.setSelected(false);
        seprai.setSelected(false);
        selimut.setSelected(false);
        boneka.setSelected(false);
        bajubahankhusus.setSelected(false);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_buttonresetpembeliActionPerformed

    private void buttonbuktipembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbuktipembeliActionPerformed
        // TODO add your handling code here:
         tampilkanNota();
    }//GEN-LAST:event_buttonbuktipembeliActionPerformed

    private void editpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpembeliActionPerformed
        // TODO add your handling code here:
        try {
            String nama = namapembeli.getText();

            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama pemesan harus diisi jika ingin mengedit Pesanan.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!isEditing) {
                BagianPembeli pemesanan = Pemesanan.getPesanan(nama);

                if (pemesanan != null) {
                    int id = pemesanan.getId();
                    namapembeli.setText(pemesanan.getNamaPembeli());
                    totalberatpembeli.setText(String.valueOf(pemesanan.getTotalBerat()));
                    alamatpembeli.setText(pemesanan.getAlamat());
                    tanggalpesanpembeli.setText(pemesanan.getTanggalPesan());
                    
                    String[] jenisBajuArray = pemesanan.getJenisBaju().split(", ");
                    baju.setSelected(Arrays.asList(jenisBajuArray).contains("Baju"));
                    seprai.setSelected(Arrays.asList(jenisBajuArray).contains("Seprai"));
                    selimut.setSelected(Arrays.asList(jenisBajuArray).contains("Selimut"));
                    boneka.setSelected(Arrays.asList(jenisBajuArray).contains("Boneka"));
                    bajubahankhusus.setSelected(Arrays.asList(jenisBajuArray).contains("Baju Bahan Khusus"));

                    cucikering.setSelected("Cuci Kering".equals(pemesanan.getJenisLayanan()));
                    cucibasah.setSelected("Cuci Basah".equals(pemesanan.getJenisLayanan()));
                    ketiganya.setSelected("Cuci Kering, Cuci Basah, Setrika".equals(pemesanan.getJenisLayanan()));

                    highquality.setSelected("High Quality".equals(pemesanan.getJenisPaket()));
                    reguler.setSelected("Reguler".equals(pemesanan.getJenisPaket()));

                    isEditing = true;
                    JOptionPane.showMessageDialog(null, "Data ditemukan. Silakan edit dan klik tombol Edit lagi untuk menyimpan perubahan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan untuk nama pemesan: " + nama, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
     

                String nama_pembeli = namapembeli.getText();
                int total_berat = Integer.parseInt(totalberatpembeli.getText());
                String alamat = alamatpembeli.getText();
                String tgl_pesan = tanggalpesanpembeli.getText();

                String jenis_baju = "";
                if (baju.isSelected()) {
                    jenis_baju = "Baju";
                } else if (seprai.isSelected()) {
                    jenis_baju = "Seprai";
                } else if (selimut.isSelected()) {
                    jenis_baju = "Selimut";
                } else if (boneka.isSelected()) {
                    jenis_baju = "Boneka";
                } else if (bajubahankhusus.isSelected()) {
                    jenis_baju = "Baju Bahan Khusus";
                }

                if (jenis_baju.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Silakan pilih Jenis Baju Anda.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String jenis_layanan = "";
                if (cucikering.isSelected()) jenis_layanan = "Cuci Kering";
                else if (cucibasah.isSelected()) jenis_layanan = "Cuci Basah";
                else if (ketiganya.isSelected()) jenis_layanan = "Cuci Kering, Cuci Basah, Setrika";

                String jenis_paket = highquality.isSelected() ? "High Quality" : "Reguler";

                BagianPembeli pemesanan = new BagianPembeli (id, total_berat, nama_pembeli, alamat, tgl_pesan, jenis_baju, jenis_layanan, jenis_paket);
                Pemesanan.updatePembeli(pemesanan);

                JOptionPane.showMessageDialog(null, "Data berhasil diubah.", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                isEditing = false;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak valid: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editpembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembeliLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembeliLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembeliLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembeliLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            AdminLaundry adminLaundry = new AdminLaundry();
            PembeliLaundry pembeliLaundry = new PembeliLaundry(adminLaundry);

            pembeliLaundry.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NamaBukti;
    private javax.swing.JTextField alamatpembeli;
    private javax.swing.JCheckBox baju;
    private javax.swing.JCheckBox bajubahankhusus;
    private javax.swing.JCheckBox boneka;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonbatalpembeli;
    private javax.swing.JButton buttonbuktipembeli;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonkembalipembeli;
    private javax.swing.JButton buttonpesansekarangpebeli;
    private javax.swing.JButton buttonresetpembeli;
    private javax.swing.JRadioButton cucibasah;
    private javax.swing.JRadioButton cucikering;
    private javax.swing.JButton editpembeli;
    private javax.swing.JTextArea hasilbuktipembeli;
    private javax.swing.JRadioButton highquality;
    private javax.swing.JTextField idpembeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton ketiganya;
    private javax.swing.JTextField namapembeli;
    private javax.swing.JRadioButton reguler;
    private javax.swing.JCheckBox selimut;
    private javax.swing.JCheckBox seprai;
    private javax.swing.JTextField tanggalpesanpembeli;
    private javax.swing.JTextField totalberatpembeli;
    // End of variables declaration//GEN-END:variables
}
